import type { TopicMap } from "../topicContent";

export const mlTopics: TopicMap = {
  "Supervised vs unsupervised learning": {
    summary:
      "Supervised learning maps inputs to known labels; unsupervised learning finds structure in unlabelled data.",
    keyPoints: [
      "Supervised: classification (discrete label) and regression (continuous value).",
      "Unsupervised: clustering, dimensionality reduction, anomaly detection.",
      "Semi-supervised uses a small labelled set plus a large unlabelled set.",
      "Label cost usually decides which family you can actually use.",
    ],
    diagram: `labelled data?
   |
   +-- yes --> supervised --> discrete label? --> classification
   |                        \\-> number?       --> regression
   |
   +-- no  --> unsupervised --> groups?      --> clustering
                             \\-> fewer dims? --> PCA / t-SNE`,
    deepDive: [
      "The real dividing line is not the algorithm but the data you have: if every example already carries the answer you want to predict, you are in supervised territory and the job becomes choosing a loss that matches the error you care about. If you only have raw observations with no target, the goal shifts to describing the data itself — grouping it, compressing it or spotting what does not fit.",
      "Semi-supervised and self-supervised learning sit between the two extremes and matter a lot in practice because labelling is expensive. Self-supervised pretraining (used heavily in NLP and vision) invents a proxy label from the data itself, such as predicting a masked word, and then a small supervised step (fine-tuning) adapts it to the real task.",
      "Reinforcement learning is often confused with these two but is a third family: there is no fixed dataset of correct answers, only a reward signal produced by acting in an environment. Knowing which of the three you are dealing with is usually the first filter an interviewer applies before asking about specific algorithms.",
    ],
    example: {
      title: "Classifying the same dataset two ways",
      steps: [
        "You have 10,000 customer records with purchase history but no explicit 'will churn' label.",
        "If a business analyst has manually tagged 2,000 of them as churned/not-churned, treat it as supervised: train a classifier on the labelled 2,000 and predict on the rest.",
        "If nobody has labelled anything, run k-means or hierarchical clustering on the same features to discover natural customer segments.",
        "Inspect the clusters; a human names them ('high value, low activity' etc.) — this naming step is exactly why unsupervised output needs interpretation, unlike supervised output.",
      ],
      result:
        "Same raw data, two different pipelines — the presence of labels decided the whole approach, not the data itself.",
    },
    mistakes: [
      {
        mistake: "Assuming clustering will magically produce the same segments a supervised model would have learned.",
        fix: "Clusters are found in feature space and have no obligation to match your business definition — validate them against known outcomes before trusting them.",
      },
      {
        mistake: "Using classification when the label is being predicted for future/unseen categories not present in the training labels.",
        fix: "If new classes can appear at inference time, consider open-set methods or anomaly detection instead of forcing a fixed-class classifier.",
      },
      {
        mistake: "Treating a small labelled sample as 'enough' supervision without checking it represents the full population.",
        fix: "Check the labelled subset's distribution against the full dataset; biased labels produce a biased supervised model.",
      },
    ],
    interviewQA: [
      {
        q: "Give an example each of classification, regression and clustering.",
        a: "Classification: spam vs not-spam email. Regression: predicting house price. Clustering: grouping customers by purchase behaviour with no predefined groups.",
      },
      {
        q: "When would you prefer semi-supervised learning?",
        a: "When labelling is expensive or slow but you have plenty of unlabelled data — you label a small subset, then use techniques like pseudo-labelling or self-training to leverage the rest.",
      },
      {
        q: "Is reinforcement learning supervised or unsupervised?",
        a: "Neither — it learns from a reward signal generated by interacting with an environment, not from a fixed set of labelled examples or an unlabelled dataset.",
      },
    ],
    practice: [
      "Take any tabular dataset (e.g. Titanic) and solve it both as supervised classification and as unsupervised clustering; compare what each reveals.",
      "Implement k-means from scratch on 2D synthetic data and plot the clusters.",
      "Read about self-supervised pretraining (e.g. masked language modelling) and explain why it counts as unsupervised.",
      "List 5 real-world problems and classify each as supervised, unsupervised or reinforcement learning.",
    ],
  },

  "Linear & logistic regression, regularisation": {
    summary:
      "Linear regression fits a straight line by minimising squared error. Logistic regression pushes that line through a sigmoid to output a probability.",
    keyPoints: [
      "Linear: y = w·x + b, loss = mean squared error.",
      "Logistic: p = 1 / (1 + e^-(w·x+b)), loss = binary cross-entropy.",
      "L2 (ridge) shrinks weights; L1 (lasso) drives some weights to exactly zero (feature selection).",
      "Always scale features before regularising — penalties are scale sensitive.",
    ],
    syntax: {
      lang: "text",
      code: "MSE  = (1/n) * sum((y - y_hat)^2)\nRidge = MSE + lambda * sum(w^2)\nLasso = MSE + lambda * sum(|w|)",
    },
    diagram: `linear                 logistic
 y                      p
 |     *                1 |      ____
 |   */                   |    _/
 | */                  0.5|   /
 |/  *                    | _/
 +--------- x           0 +/--------- x`,
    deepDive: [
      "Linear regression has a closed-form solution (the normal equation) when the feature matrix is well-conditioned, but in practice gradient descent is used because it scales to large datasets and generalises to models without a closed form, like logistic regression. Logistic regression is not really 'regression' in the predictive sense — it is a linear model for the log-odds of the positive class, and the sigmoid squashes that unbounded score into a valid probability.",
      "Regularisation is the mechanism that stops these otherwise simple models from overfitting when you have many correlated or noisy features. Ridge (L2) spreads weight across correlated features and keeps all of them small but nonzero, which is good when you believe most features contribute a little. Lasso (L1) is more aggressive — its diamond-shaped constraint region tends to zero out entire coefficients, effectively performing feature selection, which is useful when you expect only a few features to actually matter. Elastic net blends both when you want sparsity but also want to keep groups of correlated features together.",
      "The regularisation strength (lambda / alpha) is a hyperparameter tuned via cross-validation, not learned directly — plot a validation curve across a range of lambda values and pick the point where validation error is lowest, not where training error is lowest, since training error only ever grows as lambda increases.",
    ],
    example: {
      title: "Choosing between ridge and lasso for house price prediction",
      steps: [
        "You have 50 features (size, location dummies, age, distance to school, etc.) predicting house price, with several features highly correlated (e.g. number of bathrooms and number of bedrooms).",
        "Fit plain linear regression: coefficients turn out huge and unstable because of multicollinearity.",
        "Try ridge with lambda tuned by 5-fold CV: coefficients shrink and stabilise, all 50 features remain.",
        "Try lasso: 15 features get driven to exactly zero, leaving a simpler, more interpretable 35-feature model.",
        "Compare validation RMSE of both; if similar, prefer lasso for interpretability.",
      ],
      result: "Lasso gives a simpler model with comparable accuracy by eliminating redundant correlated features.",
    },
    mistakes: [
      {
        mistake: "Applying L1/L2 penalty before standardising features, so a feature measured in thousands gets penalised far more than one measured in single digits.",
        fix: "Always standardise (zero mean, unit variance) features before fitting a regularised model.",
      },
      {
        mistake: "Using accuracy-style thinking on logistic regression's raw sigmoid output without calibrating the decision threshold to the business problem.",
        fix: "Choose the classification threshold based on the precision/recall trade-off required, not by defaulting to 0.5.",
      },
      {
        mistake: "Interpreting logistic regression coefficients like linear regression coefficients (as direct effect on y).",
        fix: "Coefficients in logistic regression represent change in log-odds; exponentiate them to get odds ratios for interpretation.",
      },
    ],
    interviewQA: [
      {
        q: "Why can't we use mean squared error as the loss for logistic regression?",
        a: "MSE with a sigmoid output is non-convex, so gradient descent can get stuck in local minima; binary cross-entropy is convex for logistic regression and penalises confident wrong predictions much more heavily.",
      },
      {
        q: "What's the difference between L1 and L2 regularisation geometrically?",
        a: "L2's constraint region is a circle/sphere, so the optimum touches it smoothly and shrinks weights continuously toward zero. L1's constraint region is a diamond with corners on the axes, so the optimum often lands exactly on an axis, forcing some weights to zero.",
      },
      {
        q: "How do you interpret a logistic regression coefficient of 0.7 for a feature?",
        a: "A one-unit increase in that feature increases the log-odds of the positive class by 0.7, equivalent to multiplying the odds by e^0.7 ≈ 2.01.",
      },
      {
        q: "What happens if two features are perfectly collinear in linear regression?",
        a: "The normal equation becomes singular (not invertible), so the closed-form solution is undefined; regularisation (ridge) fixes this by adding lambda*I, which restores invertibility.",
      },
    ],
    practice: [
      "Implement linear regression using gradient descent from scratch and compare with sklearn's closed-form solution.",
      "Fit ridge and lasso on a dataset with engineered collinear features and compare which coefficients survive.",
      "Plot the sigmoid function and manually compute log-odds for a few probability values.",
      "Build a logistic regression spam classifier and tune the decision threshold using a precision-recall curve.",
      "Derive the gradient of mean squared error with respect to w by hand.",
    ],
  },

  "Decision trees, random forest, gradient boosting": {
    summary:
      "A decision tree splits data on the feature that best reduces impurity. Forests average many trees; boosting builds trees that fix the previous one's errors.",
    keyPoints: [
      "Split criteria: Gini impurity or entropy (classification), variance (regression).",
      "A single deep tree overfits; limit depth, min samples per leaf, or prune.",
      "Random forest = bagging + random feature subsets -> variance reduction, parallel training.",
      "Boosting (XGBoost/LightGBM) = sequential, fits residuals -> bias reduction, needs learning-rate tuning.",
    ],
    diagram: `TREE                BAGGING (forest)       BOOSTING
  age<30?            T1 T2 T3 ... Tn        T1 -> resid -> T2 -> resid -> T3
  /    \\             \\  |  /  ... /               (sequential)
yes     no             average vote
 |       |
buy    salary>50k?`,
    deepDive: [
      "A decision tree is built greedily: at every node it tries every possible split on every feature and picks the one that gives the largest impurity reduction, then recurses on each child. This greedy, local decision-making is exactly why a single tree is unstable — a small change in the data can flip an early split and cascade into a completely different tree, which is the high-variance behaviour that ensembles are designed to fix.",
      "Random forest tackles variance by training many trees on bootstrap samples of the data and, at each split, only considering a random subset of features. Averaging (or majority voting for classification) over many such decorrelated trees cancels out individual trees' noise while keeping bias roughly the same as a single deep tree, since each tree is still allowed to grow deep. Because each tree is independent, training is embarrassingly parallel.",
      "Gradient boosting instead tackles bias: it starts with a weak model (often a shallow tree) and repeatedly adds new shallow trees that predict the residual error (or more precisely, the negative gradient of the loss) of the current ensemble. Because each new tree depends on all previous ones, boosting is sequential and cannot be trivially parallelised across trees, but it usually reaches lower error with fewer, shallower trees than bagging. The learning rate scales down each new tree's contribution, trading training speed for better generalisation — a low learning rate with many trees usually beats a high learning rate with few trees.",
    ],
    example: {
      title: "Diagnosing overfitting in a single decision tree vs a forest",
      steps: [
        "Train a decision tree with no max_depth on a churn dataset; training accuracy hits 99.8% but validation accuracy is 78%.",
        "Limit max_depth to 5 and set min_samples_leaf to 20; training accuracy drops to 88% but validation rises to 85% — the gap shrinks.",
        "Instead of tuning one tree by hand, train a random forest with 200 trees, default depth, and no manual pruning.",
        "The forest's validation accuracy reaches 89% without needing careful depth tuning, because averaging suppresses each tree's overfitting.",
        "Finally try XGBoost with 150 shallow trees (depth 3) and learning rate 0.05; validation accuracy reaches 91% with proper early stopping on a held-out set.",
      ],
      result: "Ensembling (forest, then boosting) outperforms a hand-tuned single tree with far less manual effort.",
    },
    mistakes: [
      {
        mistake: "Growing a single decision tree to full depth and reporting training accuracy as the model's performance.",
        fix: "Always evaluate on a held-out validation/test set, and constrain depth or leaf size to control overfitting.",
      },
      {
        mistake: "Assuming random forest needs feature scaling like linear models.",
        fix: "Tree-based models split on thresholds per feature independently, so scaling has no effect — skip it and save time.",
      },
      {
        mistake: "Setting a high learning rate with many boosting rounds, causing the model to overfit or diverge.",
        fix: "Pair a low learning rate (0.01-0.1) with more trees and use early stopping on a validation set to pick the optimal round count.",
      },
    ],
    interviewQA: [
      {
        q: "Why does random forest reduce variance but not bias much?",
        a: "Each tree is grown deep (low bias, high variance) on a bootstrap sample; averaging many such trees cancels out their independent noise (variance) but doesn't change what they're systematically unable to model (bias), since all trees see similar signal.",
      },
      {
        q: "How is gradient boosting different from random forest in terms of what each new model does?",
        a: "Random forest trees are trained independently and in parallel on different data/feature subsets and then averaged. Boosting trees are trained sequentially, each one specifically fitting the errors (residuals/gradients) left by the ensemble so far.",
      },
      {
        q: "What is the effect of increasing tree depth on bias and variance?",
        a: "Deeper trees fit the training data more closely (lower bias) but become more sensitive to the specific training sample (higher variance), increasing overfitting risk.",
      },
      {
        q: "Why do gradient boosting libraries like XGBoost use shallow trees (depth 3-6) instead of deep ones?",
        a: "Shallow trees are weak learners with high bias but low variance; boosting's sequential error-correction reduces the bias over many rounds, so starting with weak learners avoids overfitting that deep trees combined with boosting would cause.",
      },
    ],
    practice: [
      "Visualise a decision tree trained on the Iris dataset and manually trace a prediction path.",
      "Train trees with depth 2, 5, 10, None on the same data and plot train vs validation accuracy against depth.",
      "Compare training time and accuracy of RandomForestClassifier vs XGBoostClassifier on the same dataset.",
      "Plot feature importances from a random forest and a gradient boosting model and compare rankings.",
      "Implement early stopping with a validation set in XGBoost and observe how many rounds it actually uses.",
    ],
  },

  "SVM & kernel intuition": {
    summary:
      "An SVM finds the hyperplane with the largest margin between classes. Kernels compute similarity in a higher-dimensional space without building it.",
    keyPoints: [
      "Support vectors are the few points that touch the margin and define the boundary.",
      "C controls the margin/violation trade-off: small C = wider margin, more slack.",
      "RBF kernel handles non-linear boundaries; gamma sets how local each point's influence is.",
      "Scale features — SVMs are distance based.",
    ],
    diagram: `  o o   |     x x
  o     |  m   x       | = hyperplane
  o  o  | a |    x     m/a = margin band
        |           x
support vectors = points on the dashed margin lines`,
    deepDive: [
      "The core idea of SVM is to maximise the margin — the distance between the decision boundary and the nearest points of each class — because a wider margin generally generalises better on unseen data. The optimisation only depends on the points closest to the boundary (the support vectors); every other point could be deleted without changing the solution, which is why SVMs can be memory-efficient at prediction time even on large training sets.",
      "The kernel trick is what makes SVMs powerful for non-linear problems: instead of explicitly mapping data into a high-dimensional feature space (which could be computationally infeasible or even infinite-dimensional), a kernel function computes the dot product of two points as if they had been mapped there, without ever performing the mapping. The RBF (Gaussian) kernel is the most common non-linear choice; gamma controls how far the influence of a single point reaches — high gamma means only nearby points matter (risk of overfitting), low gamma means far points also matter (risk of underfitting, boundary too smooth).",
      "The C parameter is a soft-margin trade-off: a large C heavily penalises misclassified/margin-violating points, producing a narrower margin that fits the training data closely (higher variance); a small C tolerates more violations for a wider, smoother margin (higher bias, more regularised). In practice, C and gamma (for RBF) are tuned together via grid search with cross-validation, because they interact — a very small gamma can make C's effect negligible and vice versa.",
    ],
    example: {
      title: "Tuning C and gamma for a non-linearly separable dataset",
      steps: [
        "Plot a 2D synthetic dataset shaped like two interleaving moons — clearly not linearly separable.",
        "Fit a linear-kernel SVM: accuracy is poor (~75%) since no straight line separates the moons.",
        "Switch to RBF kernel with default gamma and C: accuracy jumps to ~92% because RBF can bend the boundary.",
        "Grid search C in [0.1, 1, 10, 100] and gamma in [0.01, 0.1, 1, 10] using 5-fold CV.",
        "Best combination (say C=10, gamma=1) gives ~97% validation accuracy with a boundary that hugs the moons without overfitting individual points.",
      ],
      result: "Correct kernel choice plus tuned C/gamma turns an unusable linear SVM into a 97%-accurate classifier.",
    },
    mistakes: [
      {
        mistake: "Feeding raw unscaled features (e.g. income in lakhs alongside age in years) into an SVM.",
        fix: "Standardise or normalise all features first, since SVM decision boundaries depend directly on distances.",
      },
      {
        mistake: "Setting gamma very high 'to be safe' and getting near-perfect training accuracy but poor test accuracy.",
        fix: "Recognise this as classic overfitting from an overly local kernel; reduce gamma and re-tune with cross-validation.",
      },
      {
        mistake: "Using SVM on a very large dataset (hundreds of thousands of rows) and being surprised training is extremely slow.",
        fix: "Standard kernel SVM training scales poorly (roughly quadratic to cubic in samples); use linear SVM (liblinear/SGD) or switch to a tree/boosting model for large data.",
      },
    ],
    interviewQA: [
      {
        q: "What are support vectors and why do they matter?",
        a: "Support vectors are the training points closest to the decision boundary that the margin is defined against; the SVM solution depends only on them, so removing any non-support-vector point does not change the boundary.",
      },
      {
        q: "Explain the kernel trick in one sentence.",
        a: "It computes the inner product of two points as if they were transformed into a higher-dimensional space, without ever explicitly performing that transformation, making non-linear decision boundaries computationally feasible.",
      },
      {
        q: "What does a very large C value do?",
        a: "It heavily penalises margin violations, producing a narrow margin that fits the training data tightly — increasing variance/overfitting risk.",
      },
      {
        q: "Why is feature scaling critical for SVMs but not for decision trees?",
        a: "SVMs rely on distances/dot products between points to define margins, so features with larger numeric ranges dominate the distance calculation; trees split each feature independently on thresholds, so scale doesn't affect them.",
      },
    ],
    practice: [
      "Plot decision boundaries of a linear vs RBF SVM on the same 2D dataset.",
      "Grid search C and gamma on a real dataset (e.g. breast cancer) and plot a heatmap of validation accuracy.",
      "Manually identify support vectors from a small fitted SVM using sklearn's support_vectors_ attribute.",
      "Compare training time of SVM vs logistic regression as dataset size grows from 1k to 100k rows.",
    ],
  },

  "Clustering: k-means, hierarchical, DBSCAN": {
    summary:
      "Clustering groups similar points without labels. Each algorithm assumes a different cluster shape.",
    keyPoints: [
      "k-means: pick k, assign to nearest centroid, recompute — assumes round, similar-sized clusters.",
      "Choose k with the elbow method or silhouette score.",
      "Hierarchical: merge closest pairs into a dendrogram; cut it at any height.",
      "DBSCAN: density based, finds arbitrary shapes and labels outliers as noise, no k needed.",
    ],
    diagram: `k-means         hierarchical        DBSCAN
 (o o)          |   ___            ooooo  . <- noise
  C1            |  |   |          o     o
 (x x)          | _|_  |_         ooooo
  C2            A  B  C  D      arbitrary shape`,
    deepDive: [
      "k-means alternates two steps until convergence: assign every point to its nearest centroid, then move each centroid to the mean of its assigned points. It always converges but only to a local optimum, so results depend on initialisation — k-means++ initialisation (spreading initial centroids apart) is standard practice to avoid poor local minima. Because it uses Euclidean distance to a single mean, it implicitly assumes clusters are roughly spherical and similar in size and density; it struggles badly with elongated, nested or very differently-sized clusters.",
      "Hierarchical clustering builds a full tree (dendrogram) of nested clusters, either bottom-up (agglomerative: start with every point as its own cluster and repeatedly merge the closest pair) or top-down (divisive). The linkage method (single, complete, average, Ward) decides how 'distance between clusters' is defined and dramatically changes the shape of resulting clusters. Its big advantage is that you don't have to fix k upfront — you cut the dendrogram at whatever height gives the number of clusters you want, which is useful for exploratory analysis, but it's O(n²) or worse in memory and time, so it doesn't scale to huge datasets.",
      "DBSCAN defines clusters as dense regions separated by sparse regions, using two parameters: eps (neighbourhood radius) and min_samples (minimum points to form a dense region). It naturally handles arbitrarily shaped clusters and explicitly labels sparse points as noise/outliers rather than forcing them into a cluster, which k-means cannot do. Its weakness is sensitivity to eps and difficulty with clusters of very different densities, since a single eps must work globally (HDBSCAN relaxes this by using a range of densities).",
    ],
    example: {
      title: "Choosing the right algorithm for three different datasets",
      steps: [
        "Dataset A: customer age vs spending, roughly forming 3 round blobs of similar size. Run k-means with k=3 chosen via the elbow method — clean, fast clusters.",
        "Dataset B: gene expression data where you want to explore cluster structure at multiple granularities. Run agglomerative clustering with Ward linkage and inspect the dendrogram at different cut heights.",
        "Dataset C: GPS pings forming irregular, snake-like paths with scattered noise pings. Run DBSCAN with eps tuned via a k-distance plot — it correctly separates the paths and flags noise pings instead of forcing them into a path cluster.",
        "Running k-means on Dataset C for comparison would incorrectly split the snake-shaped path into several round chunks — demonstrating why algorithm choice must match the data's actual shape.",
      ],
      result: "Matching the algorithm's cluster-shape assumption to the data's actual geometry is more important than the algorithm's popularity.",
    },
    mistakes: [
      {
        mistake: "Running k-means without scaling features, so one high-magnitude feature dominates the Euclidean distance.",
        fix: "Standardise all features before computing distances in any distance-based clustering method.",
      },
      {
        mistake: "Picking k arbitrarily (e.g. always k=3) without checking elbow plot or silhouette score.",
        fix: "Run k-means for a range of k values, plot inertia (elbow) and/or silhouette score, and pick k at the bend or peak.",
      },
      {
        mistake: "Applying k-means to non-globular clusters (e.g. concentric circles) and being confused by poor results.",
        fix: "Recognise the cluster shape assumption of k-means; switch to DBSCAN or spectral clustering for non-convex shapes.",
      },
    ],
    interviewQA: [
      {
        q: "Why does k-means need the number of clusters k specified in advance, and how do you choose it?",
        a: "k-means optimises assignment given a fixed number of centroids, so k is a required input; it's chosen by running the algorithm across a range of k values and using the elbow method on inertia or maximising silhouette score.",
      },
      {
        q: "What is a key limitation of k-means that DBSCAN solves?",
        a: "k-means assumes roughly spherical, similar-sized clusters and forces every point into a cluster; DBSCAN can find arbitrarily shaped, differently-sized clusters and explicitly marks outliers as noise instead of forcing them in.",
      },
      {
        q: "What does the linkage criterion control in hierarchical clustering?",
        a: "It defines how the distance between two clusters (not two points) is computed — e.g. single linkage uses the minimum pairwise distance, complete uses the maximum, average uses the mean, and Ward minimises the increase in within-cluster variance — and this changes the shape and compactness of resulting clusters.",
      },
      {
        q: "How would you evaluate clustering quality without ground-truth labels?",
        a: "Use internal metrics like silhouette score (how similar a point is to its own cluster vs the nearest other cluster) or Davies-Bouldin index; if partial labels exist, compare with external metrics like adjusted Rand index.",
      },
    ],
    practice: [
      "Implement k-means from scratch (assign + recompute loop) and verify it matches sklearn's output.",
      "Plot an elbow curve and a silhouette score curve for k=2 to 10 on a real dataset.",
      "Cluster the same non-convex synthetic dataset with k-means and DBSCAN and compare visually.",
      "Build a dendrogram with scipy and try cutting it at different heights to get different numbers of clusters.",
      "Tune DBSCAN's eps using a k-distance plot on a spatial dataset.",
    ],
  },

  "Dimensionality reduction: PCA, t-SNE": {
    summary:
      "Reduce feature count while keeping information. PCA keeps directions of maximum variance; t-SNE preserves local neighbourhoods for visualisation.",
    keyPoints: [
      "PCA is linear, deterministic, invertible-ish, and needs standardised features.",
      "Pick components by cumulative explained variance (e.g. 95%).",
      "t-SNE/UMAP are for plotting only — distances between clusters are not meaningful.",
      "Reducing dimensions fights the curse of dimensionality and speeds training.",
    ],
    diagram: `original 2D            PCA rotation
  x2   * *              PC1 -> direction of max variance
  |   * *  *            PC2 -> orthogonal, less variance
  |  * *                keep PC1 only => 2D becomes 1D
  +--------- x1`,
    deepDive: [
      "PCA finds a new orthogonal coordinate system (the principal components) ordered by how much variance of the data they capture. Mathematically, this comes from the eigenvectors of the covariance matrix (or equivalently, SVD of the standardised data matrix); the eigenvector with the largest eigenvalue is PC1. Because PCA is a linear transformation, it can be applied to new data with the same rotation matrix learned on training data, and it can be partially inverted to reconstruct an approximation of the original features — this is why it's used both for compression and for noise reduction.",
      "The trade-off in PCA is how many components to keep: too few loses information (underfitting downstream models), too many keeps noise. The standard approach is to plot cumulative explained variance ratio against number of components and pick the smallest number that captures a target proportion (often 90-99%), or use a scree plot and look for the 'elbow' where marginal variance gained per component flattens out.",
      "t-SNE and UMAP take a fundamentally different, non-linear approach: they try to preserve local neighbourhood structure (which points are close to which) rather than global variance directions. This makes them excellent for visualising clusters in 2D/3D but dangerous to use for anything beyond visualisation — the axes have no fixed meaning, distances between well-separated clusters are not proportional to their true separation, and results change with different random seeds and the perplexity/n_neighbors hyperparameter. Never feed t-SNE output into a downstream supervised model or use inter-cluster distances quantitatively.",
    ],
    example: {
      title: "Compressing a 50-feature dataset before training",
      steps: [
        "You have a dataset with 50 correlated numeric features and want to speed up model training and fight the curse of dimensionality.",
        "Standardise all 50 features (zero mean, unit variance) since PCA is sensitive to scale.",
        "Fit PCA and plot cumulative explained variance — it shows that 12 components capture 95% of the variance.",
        "Reduce the dataset to 12 principal components and retrain the downstream classifier.",
        "Compare accuracy and training time: accuracy is nearly identical to using all 50 features, but training is 3x faster and less prone to overfitting.",
      ],
      result: "12 PCA components replace 50 raw features with negligible accuracy loss and much faster training.",
    },
    mistakes: [
      {
        mistake: "Running PCA on unscaled features, so a feature measured in thousands dominates the first principal component purely due to its scale.",
        fix: "Always standardise features (mean 0, variance 1) before fitting PCA.",
      },
      {
        mistake: "Interpreting distances between distant clusters in a t-SNE plot as meaningful ('this cluster is twice as far from that one').",
        fix: "Treat t-SNE plots only for confirming that groups exist and are separable, not for measuring the strength or distance of separation.",
      },
      {
        mistake: "Fitting PCA separately on train and test sets (each learning its own components).",
        fix: "Fit PCA only on the training set, then use the same transformation (components) to transform the test set — exactly like scalers.",
      },
    ],
    interviewQA: [
      {
        q: "How does PCA decide which direction is the first principal component?",
        a: "It picks the direction (eigenvector of the covariance matrix) along which the projected data has the maximum variance; subsequent components are orthogonal to previous ones and capture the next largest remaining variance.",
      },
      {
        q: "Why can't you use t-SNE to reduce dimensions for a downstream classifier?",
        a: "t-SNE only tries to preserve local neighbourhood relationships for visualisation, its output has no fixed global structure, is non-deterministic, doesn't have an inverse/transform for new data, and can distort global distances — none of which are safe properties for feeding into another model.",
      },
      {
        q: "How do you decide the number of PCA components to keep?",
        a: "Plot cumulative explained variance ratio versus number of components and choose the smallest number that reaches a target threshold like 90-99%, or use a scree plot elbow.",
      },
      {
        q: "What is the curse of dimensionality and how does dimensionality reduction help?",
        a: "As the number of features grows, data becomes sparse in high-dimensional space, distances between points become less meaningful, and models need exponentially more data to generalise well; reducing dimensions concentrates the useful signal and mitigates this sparsity.",
      },
    ],
    practice: [
      "Apply PCA to the MNIST or Fashion-MNIST dataset and visualise reconstruction quality at 2, 10, 50 components.",
      "Plot a scree plot and cumulative explained variance chart for a real dataset.",
      "Run t-SNE with different perplexity values (5, 30, 100) on the same dataset and observe how the plot changes.",
      "Compare classification accuracy with raw features vs PCA-reduced features on a high-dimensional dataset.",
    ],
  },

  "Feature engineering & data leakage": {
    summary:
      "Features carry most of the model's performance. Leakage is when training data contains information unavailable at prediction time — it inflates scores and fails in production.",
    keyPoints: [
      "Common features: scaling, one-hot/target encoding, binning, ratios, date parts, text vectors.",
      "Fit scalers and encoders on train only, then transform validation/test.",
      "Time series must be split chronologically — never shuffle.",
      "A suspiciously perfect score almost always means leakage.",
    ],
    syntax: {
      lang: "python",
      code: "scaler.fit(X_train)          # fit on train only\nX_train = scaler.transform(X_train)\nX_test  = scaler.transform(X_test)",
    },
    diagram: `WRONG                        RIGHT
fit scaler on all data       split first
        |                        |
     split                  fit on train
        |                        |
  test stats leaked         transform test`,
    deepDive: [
      "Good feature engineering often matters more than the choice of algorithm, especially for tabular data — a well-constructed ratio, interaction term or date-derived feature (day of week, is_holiday) can expose a signal that no amount of model complexity would otherwise find. Common transformations include target/mean encoding for high-cardinality categoricals (which must always be computed with cross-validation folds or on train-only statistics to avoid leakage), binning continuous variables to capture non-linear thresholds, and text vectorisation (TF-IDF, embeddings) for unstructured fields.",
      "Data leakage happens whenever information from outside the legitimate training scope sneaks into feature values or the training process itself — the two most common forms are: (1) target leakage, where a feature is itself derived from or highly correlated with the future outcome (e.g. using 'total_amount_refunded' to predict 'will_return_item' when refund only happens after a return), and (2) train-test contamination, where preprocessing statistics (mean, std, target-encoding maps, vocabulary) are computed on the full dataset before splitting, so test set information subtly influences the training pipeline.",
      "Time-based data leaks in a particularly dangerous way: a random shuffle-split lets the model 'see the future' by training on rows chronologically after the ones in the test set, which never happens at real prediction time. The fix is always a chronological split (train on the past, validate/test on the future), and any feature involving aggregation (e.g. rolling averages) must only use data available up to that point in time, not the whole dataset.",
    ],
    example: {
      title: "Catching leakage in a loan default model",
      steps: [
        "A model to predict loan default gets 99.4% accuracy on the test set — a red flag for such a hard real-world problem.",
        "Inspect the feature list: one feature is 'days_since_last_payment', which is only recorded/updated after the loan enters default status.",
        "Recognise this as target leakage: the feature effectively encodes the outcome itself since it only takes extreme values once default has occurred.",
        "Remove the feature and retrain — accuracy drops to a more believable 78%, matching what similar published models achieve.",
        "Audit the remaining pipeline: confirm scalers/encoders were fit on train only and that the train/test split was done before any feature computation involving aggregates.",
      ],
      result: "Removing the leaking feature drops accuracy from an unrealistic 99.4% to a trustworthy 78% that will actually hold in production.",
    },
    mistakes: [
      {
        mistake: "Fitting a StandardScaler or target encoder on the full dataset before splitting into train/test.",
        fix: "Split first, fit all preprocessing objects only on the training fold, then apply (transform-only) to validation/test.",
      },
      {
        mistake: "Randomly shuffling time series data before splitting into train/test.",
        fix: "Always split time series chronologically, e.g. train on months 1-10, test on months 11-12.",
      },
      {
        mistake: "Including a feature that is only available after the event you're trying to predict has already happened.",
        fix: "For every feature, ask 'would this value actually be available at prediction time in production?' and drop any that fail this test.",
      },
    ],
    interviewQA: [
      {
        q: "What is data leakage and why is it dangerous?",
        a: "It's when information that wouldn't be available at real prediction time leaks into training, either through a feature correlated with the target or through preprocessing statistics computed on data outside the training fold; it inflates validation metrics but the model fails in production where that leaked information doesn't exist.",
      },
      {
        q: "How do you correctly do target encoding without leakage?",
        a: "Compute target-encoded values using only out-of-fold data (e.g. via k-fold target encoding) or compute the encoding map strictly on the training set and apply it unchanged to validation/test.",
      },
      {
        q: "Why must time series data be split chronologically instead of randomly?",
        a: "A random split lets the model train on data from after the test period, effectively letting it see the future, which never happens in production where you only ever have data up to 'now'.",
      },
      {
        q: "Give an example of a feature that causes leakage in a churn prediction model.",
        a: "A feature like 'number of support tickets closed as cancellation request' would only exist for customers who already churned, so it directly encodes the target rather than being a genuine predictive signal.",
      },
    ],
    practice: [
      "Take a dataset, deliberately introduce a leaking feature, and observe how validation accuracy becomes unrealistically high.",
      "Implement k-fold target encoding correctly for a high-cardinality categorical feature.",
      "Build a chronological train/test split function for a time series dataset and compare metrics vs a random split.",
      "Write a checklist of leakage checks and apply it to a Kaggle competition dataset.",
    ],
  },

  "Cross-validation and metric selection": {
    summary:
      "Cross-validation estimates generalisation by rotating which fold is held out. The metric must match the business cost of each error type.",
    keyPoints: [
      "k-fold (k=5/10); stratified k-fold keeps class ratios; TimeSeriesSplit for temporal data.",
      "Accuracy is misleading on imbalanced data — use precision, recall, F1 or PR-AUC.",
      "Precision = of predicted positives, how many were right; recall = of actual positives, how many we caught.",
      "Regression: MAE (robust), RMSE (penalises big misses), R².",
    ],
    diagram: `5-fold CV
fold1 [TEST][ tr ][ tr ][ tr ][ tr ]
fold2 [ tr ][TEST][ tr ][ tr ][ tr ]
fold3 [ tr ][ tr ][TEST][ tr ][ tr ]
...            score = mean of folds

confusion matrix     pred+   pred-
       actual+        TP      FN
       actual-        FP      TN`,
    deepDive: [
      "A single train/test split gives one noisy estimate of generalisation error that depends heavily on which rows happened to land in the test set, especially with small datasets. k-fold cross-validation rotates the held-out fold k times and averages the score, giving both a more stable estimate and a measure of variance (standard deviation across folds tells you how sensitive the model is to which data it sees). Stratified k-fold additionally preserves the class ratio in every fold, which matters a lot for imbalanced classification — without it, some folds could end up with almost no minority-class examples, making their score meaningless.",
      "Metric selection is really a business decision disguised as a technical one. Accuracy treats every error equally and is misleading whenever classes are imbalanced (a model predicting 'no fraud' for every transaction can be 99% accurate if fraud is 1% of transactions, while being completely useless). Precision and recall let you express asymmetric costs: precision matters when false positives are expensive (e.g. flagging a legitimate transaction as fraud annoys customers), recall matters when false negatives are expensive (e.g. missing an actual cancer case). F1 balances the two when both matter roughly equally, and PR-AUC (rather than ROC-AUC) is preferred when the positive class is rare, since ROC-AUC can look deceptively good on imbalanced data because the true-negative-heavy denominator (specificity) hides poor performance on the rare class.",
      "For regression, MAE gives the average absolute error in the same units as the target and is robust to outliers, while RMSE squares errors before averaging, which penalises large mistakes much more heavily — useful when big misses are disproportionately costly (e.g. underestimating demand and running out of stock). R² tells you the proportion of variance explained relative to a naive mean-predicting baseline, useful for communicating overall model quality but not for comparing models across different datasets or for spotting where errors concentrate.",
    ],
    example: {
      title: "Choosing a metric for a rare-disease screening model",
      steps: [
        "The dataset has 2% positive (disease present) and 98% negative cases — highly imbalanced.",
        "A naive model predicting 'negative' for everyone scores 98% accuracy — clearly useless, so accuracy is rejected as the metric.",
        "Since missing a real disease case (false negative) is far more costly than a false alarm (false positive), recall is prioritised.",
        "Use stratified 5-fold CV to make sure every fold has a representative share of positive cases, and track recall and PR-AUC across folds.",
        "Tune the classification threshold downward from 0.5 to increase recall at an acceptable cost to precision, guided by the PR curve.",
      ],
      result: "The screening model is tuned to catch 95% of real disease cases (high recall) even though this reduces overall accuracy and increases false alarms.",
    },
    mistakes: [
      {
        mistake: "Using plain accuracy to evaluate a model on a highly imbalanced dataset.",
        fix: "Switch to precision, recall, F1 or PR-AUC, and always look at the confusion matrix directly.",
      },
      {
        mistake: "Using regular k-fold (not stratified) on an imbalanced classification problem.",
        fix: "Use StratifiedKFold so every fold preserves the same class ratio as the full dataset.",
      },
      {
        mistake: "Applying standard k-fold CV to time series data, mixing future and past across folds.",
        fix: "Use TimeSeriesSplit (or a rolling-origin scheme) so every validation fold only contains data that comes after its training fold.",
      },
    ],
    interviewQA: [
      {
        q: "Why is accuracy a poor metric for imbalanced datasets?",
        a: "A model can achieve high accuracy simply by always predicting the majority class, completely ignoring the minority class that usually matters most; precision, recall or PR-AUC expose this failure while accuracy hides it.",
      },
      {
        q: "When would you optimise for recall over precision?",
        a: "When false negatives are more costly than false positives, e.g. disease screening, fraud detection, or safety-critical fault detection, where missing a real positive case is far worse than a false alarm.",
      },
      {
        q: "What's the difference between k-fold and stratified k-fold?",
        a: "Plain k-fold splits data into folds without regard to class distribution, which can leave some folds with very few or no minority-class samples; stratified k-fold ensures each fold has approximately the same class ratio as the overall dataset.",
      },
      {
        q: "Why would you choose RMSE over MAE for a regression problem?",
        a: "RMSE penalises large errors more heavily than small ones (because errors are squared before averaging), so it's preferred when large mistakes are disproportionately costly and you want the model to avoid them even at the cost of slightly more small errors.",
      },
    ],
    practice: [
      "Compute accuracy, precision, recall and F1 by hand from a small confusion matrix.",
      "Run 5-fold vs stratified 5-fold CV on an imbalanced dataset and compare the variance of fold scores.",
      "Plot a precision-recall curve and an ROC curve for the same model and compare their shapes on imbalanced data.",
      "Implement TimeSeriesSplit on a stock price dataset and explain why a random split would be wrong.",
      "Compare MAE, RMSE and R² on a regression model with and without a few extreme outliers in the test set.",
    ],
  },

  "Bias-variance trade-off, overfitting control": {
    summary:
      "Bias is error from an oversimple model; variance is error from sensitivity to the training sample. Total error is minimised between the two.",
    keyPoints: [
      "High bias = underfit: train and validation error both high.",
      "High variance = overfit: low train error, high validation error.",
      "Fix overfitting with more data, regularisation, simpler models, dropout, early stopping.",
      "Fix underfitting with more features, more capacity, less regularisation.",
    ],
    diagram: `error
  |\\                       total
  | \\        _____________/
  |  \\    __/  variance
  |   \\__/
  |  bias
  +------------------------- model complexity
        ^ sweet spot`,
    deepDive: [
      "Every model's expected test error can be decomposed into three parts: bias squared (systematic error from the model's assumptions being too simple to capture the true relationship), variance (how much the model's predictions would change if trained on a different sample of the same size), and irreducible noise (error that no model can remove, inherent to the data). As model complexity increases, bias tends to fall (the model can represent more complex relationships) while variance tends to rise (the model has more freedom to fit noise specific to the training sample) — the sweet spot is where their sum is minimised, not where either individually is smallest.",
      "Diagnosing which regime you're in is done by comparing training error to validation error: both high and close together means high bias (underfitting) — the model is too weak even for the training data it has already seen. Low training error but a large gap to validation error means high variance (overfitting) — the model has memorised training-specific noise that doesn't generalise. Learning curves (error vs training set size) make this especially clear: high-bias models plateau early with a small gap between train/validation curves, while high-variance models show a large, persistent gap that narrows slowly (if at all) as more data is added.",
      "The fixes are essentially opposite levers on the same dial: to fix underfitting, increase capacity (deeper trees, more layers/neurons, more polynomial degree, more/better features) or reduce regularisation strength; to fix overfitting, do the reverse (add regularisation like L1/L2/dropout, reduce capacity, gather more training data, use early stopping, or apply data augmentation). Ensembling is a special case — bagging (like random forest) reduces variance without hurting bias much, while boosting reduces bias, which is why understanding this trade-off explains why those specific ensemble strategies work.",
    ],
    example: {
      title: "Diagnosing and fixing a polynomial regression model",
      steps: [
        "Fit a degree-1 (linear) polynomial to clearly curved data: both train and validation MSE are high and similar — classic underfitting (high bias).",
        "Fit a degree-15 polynomial to the same data: train MSE is near zero, but validation MSE is huge — classic overfitting (high variance).",
        "Plot a learning curve for the degree-15 model: the gap between train and validation error stays large even as more data is added, confirming variance is the dominant problem.",
        "Add L2 regularisation (ridge) to the degree-15 model and tune lambda via cross-validation.",
        "The regularised degree-15 model now achieves a validation error close to a well-chosen degree-3 polynomial, showing that regularisation controls variance without needing to hand-pick model complexity.",
      ],
      result: "Regularisation converts an overfit high-degree polynomial into a model with a much smaller train-validation gap and better generalisation.",
    },
    mistakes: [
      {
        mistake: "Judging model quality using only training error, without checking the validation error.",
        fix: "Always compare training and validation error together; the gap between them tells you far more than either number alone.",
      },
      {
        mistake: "Adding regularisation to a model that is already underfitting (has high bias).",
        fix: "Check the bias/variance diagnosis first — regularisation helps overfitting but makes underfitting worse; increase capacity instead.",
      },
      {
        mistake: "Concluding a model needs more data just because it's overfitting, without checking if a learning curve actually supports that.",
        fix: "Plot a learning curve — if validation error is still dropping steeply with more data, more data helps; if it has plateaued, regularisation or a simpler model is the better fix.",
      },
    ],
    interviewQA: [
      {
        q: "How do you tell from train/validation error whether a model is overfitting or underfitting?",
        a: "If both train and validation error are high and close, the model is underfitting (high bias). If train error is low but validation error is much higher, the model is overfitting (high variance).",
      },
      {
        q: "Why does adding more training data primarily fix variance and not bias?",
        a: "A high-variance model is overly sensitive to the specific noise in its training sample; more data averages out that noise so the model's fitted parameters converge closer to the true relationship, but a high-bias model's limited functional form still can't represent the true relationship no matter how much data it sees.",
      },
      {
        q: "Why does random forest reduce variance while boosting reduces bias?",
        a: "Random forest averages many independently trained high-variance, low-bias trees, and averaging cancels out uncorrelated variance while leaving bias unchanged; boosting sequentially fits residual errors of a weak, high-bias learner, progressively reducing the systematic error the ensemble makes.",
      },
      {
        q: "What is the irreducible error component in the bias-variance decomposition?",
        a: "It's the noise inherent in the data-generating process itself (e.g. measurement error, genuinely random outcomes) that no model, however perfect, can eliminate; it sets a floor on achievable test error.",
      },
    ],
    practice: [
      "Fit polynomial regression at degrees 1, 3, 8, 15 on noisy synthetic data and plot train/validation error vs degree.",
      "Plot a learning curve (error vs training set size) for an underfitting and an overfitting model and compare shapes.",
      "Take an overfitting neural network and apply dropout, then early stopping, and compare validation curves before/after each.",
      "Explain, using the bias-variance framing, why increasing k in k-NN reduces variance but increases bias.",
    ],
  },
};
