/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInterviewsRouteImport } from './routes/_authenticated/interviews'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses.index'
import { Route as AuthenticatedDsaTopicRouteImport } from './routes/_authenticated/dsa.$topic'
import { Route as AuthenticatedLearnIndexRouteImport } from './routes/_authenticated/learn.index'
import { Route as AuthenticatedSkillsSlugRouteImport } from './routes/_authenticated/skills.$slug'
import { Route as AuthenticatedCoursesCourseIndexRouteImport } from './routes/_authenticated/courses.$course.index'
import { Route as AuthenticatedLearnBranchIndexRouteImport } from './routes/_authenticated/learn.$branch.index'
import { Route as ApiPublicHooksRefreshRecruitersRouteImport } from './routes/api/public/hooks/refresh-recruiters'
import { Route as ApiPublicHooksRefreshToolsRouteImport } from './routes/api/public/hooks/refresh-tools'
import { Route as AuthenticatedCoursesCourseTopicIndexRouteImport } from './routes/_authenticated/courses.$course.$topic.index'
import { Route as AuthenticatedCoursesCourseTopicExamRouteImport } from './routes/_authenticated/courses.$course.$topic.exam'
import { Route as AuthenticatedLearnBranchCourseIndexRouteImport } from './routes/_authenticated/learn.$branch.$course.index'
import { Route as AuthenticatedLearnBranchCourseSubRouteImport } from './routes/_authenticated/learn.$branch.$course.$sub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewsRoute = AuthenticatedInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDsaTopicRoute = AuthenticatedDsaTopicRouteImport.update({
  id: '/dsa/$topic',
  path: '/dsa/$topic',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnIndexRoute = AuthenticatedLearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillsSlugRoute = AuthenticatedSkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoursesCourseIndexRoute =
  AuthenticatedCoursesCourseIndexRouteImport.update({
    id: '/courses/$course/',
    path: '/courses/$course/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnBranchIndexRoute =
  AuthenticatedLearnBranchIndexRouteImport.update({
    id: '/learn/$branch/',
    path: '/learn/$branch/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksRefreshRecruitersRoute =
  ApiPublicHooksRefreshRecruitersRouteImport.update({
    id: '/api/public/hooks/refresh-recruiters',
    path: '/api/public/hooks/refresh-recruiters',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshToolsRoute =
  ApiPublicHooksRefreshToolsRouteImport.update({
    id: '/api/public/hooks/refresh-tools',
    path: '/api/public/hooks/refresh-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCoursesCourseTopicIndexRoute =
  AuthenticatedCoursesCourseTopicIndexRouteImport.update({
    id: '/courses/$course/$topic/',
    path: '/courses/$course/$topic/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseTopicExamRoute =
  AuthenticatedCoursesCourseTopicExamRouteImport.update({
    id: '/courses/$course/$topic/exam',
    path: '/courses/$course/$topic/exam',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnBranchCourseIndexRoute =
  AuthenticatedLearnBranchCourseIndexRouteImport.update({
    id: '/learn/$branch/$course/',
    path: '/learn/$branch/$course/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearnBranchCourseSubRoute =
  AuthenticatedLearnBranchCourseSubRouteImport.update({
    id: '/learn/$branch/$course/$sub',
    path: '/learn/$branch/$course/$sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/dsa/$topic': typeof AuthenticatedDsaTopicRoute
  '/skills/$slug': typeof AuthenticatedSkillsSlugRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/learn/': typeof AuthenticatedLearnIndexRoute
  '/api/public/hooks/refresh-recruiters': typeof ApiPublicHooksRefreshRecruitersRoute
  '/api/public/hooks/refresh-tools': typeof ApiPublicHooksRefreshToolsRoute
  '/courses/$course/': typeof AuthenticatedCoursesCourseIndexRoute
  '/learn/$branch/': typeof AuthenticatedLearnBranchIndexRoute
  '/courses/$course/$topic/exam': typeof AuthenticatedCoursesCourseTopicExamRoute
  '/learn/$branch/$course/$sub': typeof AuthenticatedLearnBranchCourseSubRoute
  '/courses/$course/$topic/': typeof AuthenticatedCoursesCourseTopicIndexRoute
  '/learn/$branch/$course/': typeof AuthenticatedLearnBranchCourseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/interviews': typeof AuthenticatedInterviewsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/dsa/$topic': typeof AuthenticatedDsaTopicRoute
  '/skills/$slug': typeof AuthenticatedSkillsSlugRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/learn': typeof AuthenticatedLearnIndexRoute
  '/api/public/hooks/refresh-recruiters': typeof ApiPublicHooksRefreshRecruitersRoute
  '/api/public/hooks/refresh-tools': typeof ApiPublicHooksRefreshToolsRoute
  '/courses/$course': typeof AuthenticatedCoursesCourseIndexRoute
  '/learn/$branch': typeof AuthenticatedLearnBranchIndexRoute
  '/courses/$course/$topic/exam': typeof AuthenticatedCoursesCourseTopicExamRoute
  '/learn/$branch/$course/$sub': typeof AuthenticatedLearnBranchCourseSubRoute
  '/courses/$course/$topic': typeof AuthenticatedCoursesCourseTopicIndexRoute
  '/learn/$branch/$course': typeof AuthenticatedLearnBranchCourseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/interviews': typeof AuthenticatedInterviewsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/dsa/$topic': typeof AuthenticatedDsaTopicRoute
  '/_authenticated/skills/$slug': typeof AuthenticatedSkillsSlugRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/learn/': typeof AuthenticatedLearnIndexRoute
  '/api/public/hooks/refresh-recruiters': typeof ApiPublicHooksRefreshRecruitersRoute
  '/api/public/hooks/refresh-tools': typeof ApiPublicHooksRefreshToolsRoute
  '/_authenticated/courses/$course/': typeof AuthenticatedCoursesCourseIndexRoute
  '/_authenticated/learn/$branch/': typeof AuthenticatedLearnBranchIndexRoute
  '/_authenticated/courses/$course/$topic/exam': typeof AuthenticatedCoursesCourseTopicExamRoute
  '/_authenticated/learn/$branch/$course/$sub': typeof AuthenticatedLearnBranchCourseSubRoute
  '/_authenticated/courses/$course/$topic/': typeof AuthenticatedCoursesCourseTopicIndexRoute
  '/_authenticated/learn/$branch/$course/': typeof AuthenticatedLearnBranchCourseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/interviews'
    | '/jobs'
    | '/profile'
    | '/projects'
    | '/roadmap'
    | '/tools'
    | '/dsa/$topic'
    | '/skills/$slug'
    | '/courses/'
    | '/learn/'
    | '/api/public/hooks/refresh-recruiters'
    | '/api/public/hooks/refresh-tools'
    | '/courses/$course/'
    | '/learn/$branch/'
    | '/courses/$course/$topic/exam'
    | '/learn/$branch/$course/$sub'
    | '/courses/$course/$topic/'
    | '/learn/$branch/$course/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/interviews'
    | '/jobs'
    | '/profile'
    | '/projects'
    | '/roadmap'
    | '/tools'
    | '/dsa/$topic'
    | '/skills/$slug'
    | '/courses'
    | '/learn'
    | '/api/public/hooks/refresh-recruiters'
    | '/api/public/hooks/refresh-tools'
    | '/courses/$course'
    | '/learn/$branch'
    | '/courses/$course/$topic/exam'
    | '/learn/$branch/$course/$sub'
    | '/courses/$course/$topic'
    | '/learn/$branch/$course'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/interviews'
    | '/_authenticated/jobs'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/roadmap'
    | '/_authenticated/tools'
    | '/_authenticated/dsa/$topic'
    | '/_authenticated/skills/$slug'
    | '/_authenticated/courses/'
    | '/_authenticated/learn/'
    | '/api/public/hooks/refresh-recruiters'
    | '/api/public/hooks/refresh-tools'
    | '/_authenticated/courses/$course/'
    | '/_authenticated/learn/$branch/'
    | '/_authenticated/courses/$course/$topic/exam'
    | '/_authenticated/learn/$branch/$course/$sub'
    | '/_authenticated/courses/$course/$topic/'
    | '/_authenticated/learn/$branch/$course/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksRefreshRecruitersRoute: typeof ApiPublicHooksRefreshRecruitersRoute
  ApiPublicHooksRefreshToolsRoute: typeof ApiPublicHooksRefreshToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interviews': {
      id: '/_authenticated/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof AuthenticatedInterviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dsa/$topic': {
      id: '/_authenticated/dsa/$topic'
      path: '/dsa/$topic'
      fullPath: '/dsa/$topic'
      preLoaderRoute: typeof AuthenticatedDsaTopicRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/': {
      id: '/_authenticated/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedLearnIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/$slug': {
      id: '/_authenticated/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof AuthenticatedSkillsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$course/': {
      id: '/_authenticated/courses/$course/'
      path: '/courses/$course'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$branch/': {
      id: '/_authenticated/learn/$branch/'
      path: '/learn/$branch'
      fullPath: '/learn/$branch/'
      preLoaderRoute: typeof AuthenticatedLearnBranchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/refresh-recruiters': {
      id: '/api/public/hooks/refresh-recruiters'
      path: '/api/public/hooks/refresh-recruiters'
      fullPath: '/api/public/hooks/refresh-recruiters'
      preLoaderRoute: typeof ApiPublicHooksRefreshRecruitersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-tools': {
      id: '/api/public/hooks/refresh-tools'
      path: '/api/public/hooks/refresh-tools'
      fullPath: '/api/public/hooks/refresh-tools'
      preLoaderRoute: typeof ApiPublicHooksRefreshToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses/$course/$topic/': {
      id: '/_authenticated/courses/$course/$topic/'
      path: '/courses/$course/$topic'
      fullPath: '/courses/$course/$topic/'
      preLoaderRoute: typeof AuthenticatedCoursesCourseTopicIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$course/$topic/exam': {
      id: '/_authenticated/courses/$course/$topic/exam'
      path: '/courses/$course/$topic/exam'
      fullPath: '/courses/$course/$topic/exam'
      preLoaderRoute: typeof AuthenticatedCoursesCourseTopicExamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$branch/$course/': {
      id: '/_authenticated/learn/$branch/$course/'
      path: '/learn/$branch/$course'
      fullPath: '/learn/$branch/$course/'
      preLoaderRoute: typeof AuthenticatedLearnBranchCourseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$branch/$course/$sub': {
      id: '/_authenticated/learn/$branch/$course/$sub'
      path: '/learn/$branch/$course/$sub'
      fullPath: '/learn/$branch/$course/$sub'
      preLoaderRoute: typeof AuthenticatedLearnBranchCourseSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInterviewsRoute: typeof AuthenticatedInterviewsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedDsaTopicRoute: typeof AuthenticatedDsaTopicRoute
  AuthenticatedSkillsSlugRoute: typeof AuthenticatedSkillsSlugRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedLearnIndexRoute: typeof AuthenticatedLearnIndexRoute
  AuthenticatedCoursesCourseIndexRoute: typeof AuthenticatedCoursesCourseIndexRoute
  AuthenticatedLearnBranchIndexRoute: typeof AuthenticatedLearnBranchIndexRoute
  AuthenticatedCoursesCourseTopicExamRoute: typeof AuthenticatedCoursesCourseTopicExamRoute
  AuthenticatedLearnBranchCourseSubRoute: typeof AuthenticatedLearnBranchCourseSubRoute
  AuthenticatedCoursesCourseTopicIndexRoute: typeof AuthenticatedCoursesCourseTopicIndexRoute
  AuthenticatedLearnBranchCourseIndexRoute: typeof AuthenticatedLearnBranchCourseIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInterviewsRoute: AuthenticatedInterviewsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedDsaTopicRoute: AuthenticatedDsaTopicRoute,
  AuthenticatedSkillsSlugRoute: AuthenticatedSkillsSlugRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedLearnIndexRoute: AuthenticatedLearnIndexRoute,
  AuthenticatedCoursesCourseIndexRoute: AuthenticatedCoursesCourseIndexRoute,
  AuthenticatedLearnBranchIndexRoute: AuthenticatedLearnBranchIndexRoute,
  AuthenticatedCoursesCourseTopicExamRoute:
    AuthenticatedCoursesCourseTopicExamRoute,
  AuthenticatedLearnBranchCourseSubRoute:
    AuthenticatedLearnBranchCourseSubRoute,
  AuthenticatedCoursesCourseTopicIndexRoute:
    AuthenticatedCoursesCourseTopicIndexRoute,
  AuthenticatedLearnBranchCourseIndexRoute:
    AuthenticatedLearnBranchCourseIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksRefreshRecruitersRoute: ApiPublicHooksRefreshRecruitersRoute,
  ApiPublicHooksRefreshToolsRoute: ApiPublicHooksRefreshToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
