CREATE TABLE public.recruiters (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  company TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL,
  hiring_status TEXT NOT NULL DEFAULT 'Actively hiring',
  hiring_window TEXT,
  branches TEXT[] NOT NULL DEFAULT '{}',
  skills TEXT[] NOT NULL DEFAULT '{}',
  project_expectations TEXT,
  interview_process TEXT,
  ctc_range TEXT,
  eligibility TEXT,
  url TEXT,
  added_week DATE NOT NULL DEFAULT date_trunc('week', now())::date,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.recruiters TO anon;
GRANT SELECT ON public.recruiters TO authenticated;
GRANT ALL ON public.recruiters TO service_role;

ALTER TABLE public.recruiters ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Recruiters are publicly readable" ON public.recruiters FOR SELECT TO anon, authenticated USING (true);

INSERT INTO public.job_state (job_name) VALUES ('weekly_recruiters_refresh')
ON CONFLICT (job_name) DO NOTHING;

INSERT INTO public.recruiters (company, role, hiring_status, hiring_window, branches, skills, project_expectations, interview_process, ctc_range, eligibility, url) VALUES
('Amazon', 'SDE-1 / SDE Intern', 'Actively hiring', 'Aug-Nov (campus + off-campus SDE hiring challenge)', '{CSE,IT,AIML,DS}', '{"DSA (graphs, DP, trees)","System design basics","One language deeply (Java/C++/Python)","OS & DBMS fundamentals","Leadership Principles / behavioural"}', 'One scalable full-stack or distributed-systems project you can defend end to end — clear ownership, real deployment, measurable scale numbers.', 'Online assessment (2 coding + workstyle) → 2-3 technical rounds (DSA + LP) → bar raiser', '₹28-45 LPA (SDE-1)', '60%+ aggregate, no active backlogs', 'https://www.amazon.jobs/en/teams/university-talent-acquisition'),
('Microsoft', 'Software Engineer / SWE Intern', 'Actively hiring', 'Jul-Sep (Engage + campus drives)', '{CSE,IT,AIML}', '{"DSA (arrays, strings, trees, DP)","Low-level design + OOP","OS, CN fundamentals","Debugging & code reading","Cloud basics (Azure)"}', 'Projects that solve a real user problem with clean architecture; internal quality (tests, error handling) is probed more than feature count.', 'Online round → 2-3 technical interviews (code + design) → AA (as-appropriate) round', '₹45-55 LPA (incl. stock + bonus)', '7.0+ CGPA typically', 'https://careers.microsoft.com/students'),
('Google', 'Software Engineer / STEP Intern', 'Actively hiring', 'Rolling; STEP intern applications Jan-Mar', '{CSE,IT,AIML,DS}', '{"Advanced DSA & problem solving","Complexity analysis rigour","System design (for full-time)","Coding hygiene","Maths/discrete reasoning"}', 'Depth over breadth — one algorithmically non-trivial project, open-source contribution, or research work with real users or citations.', 'Online sample → 2 phone/technical screens → 3-4 onsite rounds → hiring committee', '₹50-65 LPA', 'Strong CGPA + competitive programming record helps', 'https://www.google.com/about/careers/applications/students/'),
('TCS', 'Systems Engineer (NQT / Digital / Prime)', 'Actively hiring', 'NQT windows: Jun-Aug and Nov-Jan', '{CSE,IT,AIML,DS}', '{"Aptitude & verbal ability","Programming logic (C/Java/Python)","DBMS & SQL","OS & CN theory","Communication / email writing"}', 'Any working full-stack or database-driven project; they mainly test whether you can explain your own code and tech choices.', 'TCS NQT (aptitude + coding) → technical interview → managerial + HR round', '₹3.36-9 LPA (Ninja/Digital/Prime bands)', '60%+ in 10th, 12th and degree; max 1 year gap', 'https://www.tcs.com/careers/india/tcs-nqt'),
('Infosys', 'Systems Engineer / Specialist Programmer', 'Actively hiring', 'Sep-Dec (HackWithInfy for SP roles: Feb-Apr)', '{CSE,IT,AIML,DS}', '{"Aptitude & reasoning","DSA (medium for Specialist Programmer)","SQL","Java/Python fundamentals","Puzzle solving"}', 'A deployed web app or automation project. For Specialist Programmer, competitive-programming strength matters more than projects.', 'Online test → technical interview → HR round (Specialist Programmer adds a coding round)', '₹3.6 LPA (SE) / ₹9.5 LPA (Specialist Programmer)', '60%+ aggregate, no backlogs at joining', 'https://www.infosys.com/careers/students.html'),
('Wipro', 'Project Engineer (Elite NLTH) / WILP', 'Actively hiring', 'Elite NLTH: Aug-Oct', '{CSE,IT,AIML,DS}', '{"Aptitude","Written communication (essay round)","Basic coding (C/Java/Python)","DBMS","Cloud awareness"}', 'Simple but complete projects; the essay and communication round eliminates more candidates than coding does.', 'Elite NLTH (aptitude + coding + written English) → technical interview → HR', '₹3.5-6.5 LPA', '60%+ in degree, 60%+ in 10th/12th', 'https://careers.wipro.com/'),
('Accenture', 'Associate Software Engineer', 'Actively hiring', 'Sep-Jan', '{CSE,IT,AIML,DS}', '{"Cognitive & technical assessment","SQL","Networking & OS basics","Coding (any language)","Communication assessment"}', 'Cloud- or data-oriented projects stand out; they value certification-backed learning (Azure/AWS fundamentals).', 'Cognitive + technical assessment → coding round → communication assessment → interview', '₹4.6-6.5 LPA', '65%+ aggregate, no backlogs', 'https://www.accenture.com/in-en/careers'),
('Cognizant', 'Programmer Analyst / GenC Next', 'Actively hiring', 'Oct-Feb', '{CSE,IT,AIML,DS}', '{"Aptitude","DSA basics (GenC Next: medium)","SQL & DBMS","Java or Python","OOP"}', 'GenC Next expects a real coded project with GitHub history; GenC accepts academic mini-projects.', 'Online assessment → technical interview → HR (GenC Next has an extra advanced coding round)', '₹4-6.75 LPA', '60%+ aggregate', 'https://careers.cognizant.com/global/en/students'),
('Deloitte', 'Analyst — Technology / Data', 'Actively hiring', 'Aug-Dec', '{CSE,IT,DS}', '{"SQL & data modelling","Excel & Power BI/Tableau","Python or Java","Case-based problem solving","Client communication"}', 'Analytics dashboards and business case studies with a clear insight-to-recommendation story.', 'Online assessment → group/case discussion → technical interview → partner/HR round', '₹6.5-9 LPA', '60%+ aggregate', 'https://www2.deloitte.com/in/en/careers.html'),
('Goldman Sachs', 'Analyst — Engineering', 'Actively hiring', 'Jul-Sep (Engineering Campus Hiring Programme)', '{CSE,IT,AIML,DS}', '{"Strong DSA","Probability & maths","Java/C++/Python","Low latency & concurrency basics","Finance curiosity"}', 'Quantitative or performance-sensitive projects — simulations, trading bots, data pipelines with latency numbers.', 'HackerRank/CodeSignal test → 2-3 technical interviews → superday (tech + behavioural)', '₹22-32 LPA', 'Top-tier CGPA, strong aptitude', 'https://www.goldmansachs.com/careers/students/programs'),
('Zoho', 'Member Technical Staff', 'Actively hiring', 'Year-round (multi-round in-person drives)', '{CSE,IT}', '{"C/Java programming depth","DSA implementation without libraries","DBMS & SQL","Debugging","Logical reasoning"}', 'They care about hand-written implementations — build data structures, a mini database, or a small interpreter yourself.', 'Aptitude → 2 programming rounds (on paper/machine) → advanced coding → technical + HR', '₹6.5-9 LPA', 'No strict CGPA cutoff; skill-first', 'https://www.zoho.com/careers/'),
('Fractal Analytics', 'Data Scientist / Engineer — Trainee', 'Actively hiring', 'Sep-Jan', '{AIML,DS,CSE}', '{"Statistics & hypothesis testing","Classical ML + model evaluation","Python (pandas, scikit-learn)","SQL","Applied LLM/RAG basics"}', 'An end-to-end ML project with EDA, feature engineering, metric justification and deployment — not a notebook copy of a Kaggle kernel.', 'Online assessment (stats + Python) → case study → technical interview → HR', '₹9-13 LPA', '65%+ aggregate', 'https://fractal.ai/careers/'),
('Nvidia', 'Software / Deep Learning Engineer Intern', 'Actively hiring', 'Aug-Nov', '{AIML,CSE,DS}', '{"Deep learning fundamentals","CUDA / C++ performance","PyTorch","Linear algebra","Profiling & optimisation"}', 'GPU-accelerated or model-optimisation projects — quantisation, inference speedups, custom kernels, benchmarks with charts.', 'Resume shortlist → technical screen → 2-3 deep technical rounds → manager round', '₹25-40 LPA', 'Strong DL coursework or research output', 'https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting/'),
('Capgemini', 'Analyst / Senior Analyst', 'Actively hiring', 'Nov-Mar', '{CSE,IT,DS}', '{"Aptitude & pseudo-code","Game-based assessment","SQL","Java/Python basics","English communication"}', 'A functional web project plus a cloud or testing certification is enough to clear technical rounds.', 'Online assessment (aptitude + pseudo-code + game round) → technical interview → HR', '₹4.25-7.5 LPA', '60%+ aggregate, no backlogs', 'https://www.capgemini.com/in-en/careers/');